version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data: