export const publicationCategories = [
  { key: "journal", label: "Journal" },
  { key: "conference", label: "Conference" },
  { key: "bookChapter", label: "Book Chapter" },
  { key: "patent", label: "Patent" },
];

export const publicationFieldConfig = {
  Journal: {
    columns: [
      ["title", "Title"],
      ["name", "Journal Name"],
      ["category", "Category"],
      ["impactFactor", "Impact Factor"],
      ["status", "Status"],
      ["communicationDate", "Date of Communication", "date"],
      ["isbn", "ISBN"],
      ["volumeNo", "Vol No"],
      ["articleNo", "Article No"],
      ["publishedYear", "Publish Year"],
      ["link", "Link"],
    ],
  },
  Conference: {
    columns: [
      ["title", "Title"],
      ["name", "Conference Name"],
      ["scopusIndex", "Scopus Index"],
      ["conferenceDate", "Date of Conf.", "date"],
      ["conferenceVenue", "Venue of Conf."],
      ["status", "Status"],
      ["CommunicationDate", "Date of Communication", "date"],
      ["isbn", "ISBN"],
      ["volumeNo", "Vol No"],
      ["articleNo", "Article No"],
      ["publishedYear", "Publish Year"],
      ["link", "Link"],
    ],
  },
  BookChapter: {
    columns: [
      ["title", "Title"],
      ["name", "Book Name"],
      ["scopusIndex", "Scopus Index"],
      ["publisher", "Publisher"],
      ["status", "Status"],
      ["communicationDate", "Date of Communication", "date"],
      ["isbn", "ISBN"],
      ["volumeNo", "Vol No"],
      ["articleNo", "Article No"],
      ["publishedYear", "Publish Year"],
      ["link", "Link"],
    ],
  },
  Patent: {
    columns: [
      ["title", "Title"],
      ["name", "Patent Name"],
      ["applicationNo", "Application No"],
      ["status", "Status"],
      ["dateOfFiled", "Date of Filed", "date"],
      ["dateOfFer", "Date of FER", "date"],
      ["dateOfGrant", "Date of Grant", "date"],
      ["grantNo", "Grant No"],
      ["isbn", "ISBN"],
      ["volumeNo", "Vol No"],
      ["articleNo", "Article No"],
      ["publishedYear", "Publish Year"],
      ["link", "Link"],
    ],
  },
};

export const createEmptyPublication = (category) => ({
  category,
  title: "",
  publicationName: "",
  applicationNumber: "",
  scopusIndex: "",
  dateOfConference: "",
  venueOfConference: "",
  publisher: "",
  dateOfFiled: "",
  dateOfFer: "",
  dateOfGrant: "",
  grantNumber: "",
  publicationType: "",
  impactFactor: "",
  status: "",
  dateOfCommunication: "",
  isbn: "",
  volumeNumber: "",
  articleNumber: "",
  publishYear: "",
  link: "",
});
